version: '3.7'

services:
  web:
    build:
      context: .
      dockerfile: docker/compose/prod/api/Dockerfile
    expose:
      - 8000
  graphql-engine:
    image: hasura/graphql-engine:v1.1.0.cli-migrations
    ports:
    - 8080:8080
    restart: always
    env_file:
      - ./docker/envs/prod/hasura
    volumes:
      - ./migrations:/hasura-migrations

volumes:
  postgres_data:
