version: '3.7'

services:
  postgres:
    image: postgres:12.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - 5432:5432
    env_file:
      - ./docker/envs/local/db
  web:
    build:
      context: .
      dockerfile: ./docker/compose/local/api/Dockerfile
    restart: always
    volumes:
      - .:/usr/src/
    ports:
      - 8000:8000
    env_file:
      - ./docker/envs/local/web
  graphql-engine:
    image: hasura/graphql-engine:v1.1.0.cli-migrations
    ports:
    - 8080:8080
    depends_on:
    - postgres
    restart: always
    env_file:
      - ./docker/envs/local/hasura

volumes:
  postgres_data:
