version: '3.7'

services:
  postgres:
    image: postgres:12.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB
      - POSTGRES_PASSWORD
      - POSTGRES_USER
  web:
    build:
      context: .
      dockerfile: ./compose/local/api/Dockerfile
    restart: always
    volumes:
      - .:/usr/src/
    ports:
      - 8000:8000
    env_file:
      - ./.env.dev
    environment:
      - DEBUG
  graphql-engine:
    image: hasura/graphql-engine:v1.1.0.cli-migrations
    ports:
    - 8080:8080
    depends_on:
    - postgres
    restart: always
    environment:
      - HASURA_GRAPHQL_ADMIN_SECRET
      - HASURA_GRAPHQL_DATABASE_URL
      - HASURA_GRAPHQL_ENABLE_CONSOLE
      - HASURA_GRAPHQL_ENABLED_LOG_TYPES
    volumes:
      - ./hasura/migrations:/hasura-migrations

volumes:
  postgres_data:
