version: '3.7'

services:
  web:
    build:
      context: .
      dockerfile: compose/prod/api/Dockerfile
    expose:
      - 8000
    env_file:
      - ./.env.prod
    environment:
      - DEBUG
  db:
    image: postgres:12.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env.prod.db
    environment:
      - POSTGRES_DB
      - POSTGRES_PASSWORD
      - POSTGRES_USER
  graphql-engine:
    image: hasura/graphql-engine:v1.1.0.cli-migrations
    ports:
    - 8080:8080
    depends_on:
    - db
    restart: always
    environment:
      - HASURA_GRAPHQL_ADMIN_SECRET
      - HASURA_GRAPHQL_DATABASE_URL
      - HASURA_GRAPHQL_ENABLE_CONSOLE
      - HASURA_GRAPHQL_ENABLED_LOG_TYPES
    volumes:
      - ./migrations:/hasura-migrations

volumes:
  postgres_data:
