version: '3.7'

services:
  web:
    build:
      context: .
      dockerfile: compose/prod/api/Dockerfile
    expose:
      - 8000
    env_file:
      - ./.env.prod
  db:
    image: postgres:12.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env.prod.db
  graphql-engine:
    image: hasura/graphql-engine:v1.1.0.cli-migrations
    ports:
    - 8080:8080
    depends_on:
    - db
    restart: always
    environment:
      HASURA_GRAPHQL_DATABASE_URL: postgres://hello_zm:hello_zm@db:5432/hello_zm_dev
      HASURA_GRAPHQL_ENABLE_CONSOLE: "true" # set to "false" to disable console
      HASURA_GRAPHQL_ENABLED_LOG_TYPES: startup, http-log, webhook-log, websocket-log, query-log
      HASURA_GRAPHQL_ADMIN_SECRET: dev_only_password
    volumes:
      - ./migrations:/hasura-migrations

volumes:
  postgres_data:
